FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD basicServices.jar /opt/basicServices/
EXPOSE 8080
WORKDIR /opt/basicServices/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "basicServices.jar"]
